version: 0.2

env:
  variables:
    CACHE_CONTROL: "86400"
    S3_BUCKET: "{{s3_bucket_url}}"
    BUILD_FOLDER: "dist"

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies"
      - npm install

  build:
    commands:
      - echo "Building the project"
      - npm run build
      - echo "Bucket Name: $S3_BUCKET"  # Example usage of environment variable

artifacts:
  files:
    - '**/*'
  discard-paths: yes

cache:
  paths:
    - 'node_modules/**/*'
