version: 0.2

env:
  variables:
    S3_BUCKET: "S3_BUCKET" # Replace with your actual S3 bucket name

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies"
      - npm install
      - echo "Installed dependencies successfully"

  build:
    commands:
      - echo "Verifying Node.js version"
      - node -v
      - echo "Verifying npm version"
      - npm -v
      - echo "Checking if Angular CLI is installed"
      - ng --version || npm install -g @angular/cli
      - echo "Checking file structure"
      - ls -la
      - echo "Building the project with verbose logging"
      - npm run build --verbose || (echo "Build failed" && exit 1)

  post_build:
    commands:
      - echo "Verifying build artifacts"
      - ls -la dist/demo-devops
      - echo "Deploying to S3"
      - aws s3 sync dist/demo-devops s3://$S3_BUCKET --delete
      - echo "Deployment completed"

artifacts:
  files:
    - 'dist/**/*'
  discard-paths: yes

cache:
  paths:
    - 'node_modules/**/*'
