version: 0.2

env:
  variables:
    S3_BUCKET: "S3_BUCKET" # Replace with your actual S3 bucket name

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies"
      - npm install
      - echo "Installed dependencies successfully"
  post_build:
    commands:
      - echo "Verifying build artifacts"
      - ls -la dist/demo-devops
      - echo "Deploying to S3 bucket: $S3_BUCKET"
      - aws s3 sync dist/demo-devops s3://$S3_BUCKET --delete --debug
artifacts:
  files:
    - 'dist/**/*'
  discard-paths: yes

cache:
  paths:
    - 'node_modules/**/*'
