version: 0.2

env:
  variables:
    S3_BUCKET: "my-s3-bucket-name" # Replace with your actual S3 bucket name
    ENV_VAR_1: "value1"

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies"
      - npm install

  build:
    commands:
      - echo "Building the project"
      - npm run build:prod
      - echo "Bucket Name: $S3_BUCKET"

  post_build:
    commands:
      - echo "Deploying to S3"
      - aws s3 sync dist/demo-devops s3://$S3_BUCKET --delete
      - echo "Deployment completed"

artifacts:
  files:
    - 'dist/**/*'
  discard-paths: yes

cache:
  paths:
    - 'node_modules/**/*'
