name: Deploy Angular to AWS
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build
        run: npm run build --prod
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ AWS_SECRET_ACCESS_KEY }}          
      
      - name: Deploy to S3
        run: aws s3 sync dist/demo-devops s3://${{ AWS_S3_BUCKET }}
      
      - name: Invalidate CloudFront
        if: success()
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ SECRETS_CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
