version: 0.2

env:
  variables:
    S3_BUCKET: "my-s3-bucket-name"
    ENV_VAR_1: "value1"

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing dependencies"
      - npm install

  build:
    commands:
      - echo "Building the project"
      - npm run build --prod # This builds the Angular project

  post_build:
    commands:
      - echo "Syncing files to S3"
      - aws s3 sync dist/your-project-name s3://$S3_BUCKET --delete
      - echo "Invalidating CloudFront cache (if applicable)"
      - aws cloudfront create-invalidation --distribution-id YOUR_DISTRIBUTION_ID --paths "/*" || echo "No CloudFront distribution set"

artifacts:
  files:
    - 'dist/**/*' # Collect only built Angular files
  discard-paths: yes

cache:
  paths:
    - 'node_modules/**/*'
